// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentRequest = `-- name: CreateAgentRequest :exec
INSERT INTO agent_requests (
    id, session_id, request_type, created_at, accepted_at, accepted_by, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateAgentRequestParams struct {
	ID          uuid.UUID            `json:"id"`
	SessionID   uuid.UUID            `json:"sessionId"`
	RequestType AgentRequestTypeEnum `json:"requestType"`
	CreatedAt   pgtype.Timestamptz   `json:"createdAt"`
	AcceptedAt  pgtype.Timestamptz   `json:"acceptedAt"`
	AcceptedBy  pgtype.UUID          `json:"acceptedBy"`
	Metadata    []byte               `json:"metadata"`
}

func (q *Queries) CreateAgentRequest(ctx context.Context, arg CreateAgentRequestParams) error {
	_, err := q.db.Exec(ctx, createAgentRequest,
		arg.ID,
		arg.SessionID,
		arg.RequestType,
		arg.CreatedAt,
		arg.AcceptedAt,
		arg.AcceptedBy,
		arg.Metadata,
	)
	return err
}

const getAgentRequestByID = `-- name: GetAgentRequestByID :one
SELECT id, session_id, request_type, created_at, accepted_at, accepted_by, metadata FROM agent_requests WHERE id = $1
`

func (q *Queries) GetAgentRequestByID(ctx context.Context, id uuid.UUID) (AgentRequest, error) {
	row := q.db.QueryRow(ctx, getAgentRequestByID, id)
	var i AgentRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestType,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.Metadata,
	)
	return i, err
}
