// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAuthSessionByID = `-- name: DeleteAuthSessionByID :exec
UPDATE auth_sessions SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteAuthSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthSessionByID, id)
	return err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT id, user_id, is_revoked, expires_at, created_at, deleted_at from auth_sessions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAuthSessionByID(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAuthSessionByUserID = `-- name: GetAuthSessionByUserID :many
SELECT id, user_id, is_revoked, expires_at, created_at, deleted_at from auth_sessions WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAuthSessionByUserID(ctx context.Context, userID uuid.UUID) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, getAuthSessionByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsRevoked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuthSession = `-- name: UpsertAuthSession :exec
INSERT INTO auth_sessions (
    id, user_id, created_at, expires_at, is_revoked
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (id) DO UPDATE SET
    is_revoked = EXCLUDED.is_revoked
`

type UpsertAuthSessionParams struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"userId"`
	CreatedAt time.Time   `json:"createdAt"`
	ExpiresAt time.Time   `json:"expiresAt"`
	IsRevoked pgtype.Bool `json:"isRevoked"`
}

func (q *Queries) UpsertAuthSession(ctx context.Context, arg UpsertAuthSessionParams) error {
	_, err := q.db.Exec(ctx, upsertAuthSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsRevoked,
	)
	return err
}
