// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	IsRevoked pgtype.Bool        `json:"isRevoked"`
	ExpiresAt time.Time          `json:"expiresAt"`
	CreatedAt time.Time          `json:"createdAt"`
	DeletedAt pgtype.Timestamptz `json:"deletedAt"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	FirstName  string             `json:"firstName"`
	LastName   string             `json:"lastName"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	CreatedAt  time.Time          `json:"createdAt"`
	UpdatedAt  time.Time          `json:"updatedAt"`
	VerifiedAt pgtype.Timestamptz `json:"verifiedAt"`
	DeletedAt  pgtype.Timestamptz `json:"deletedAt"`
}
