// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
