// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAgentRequest(ctx context.Context, arg CreateAgentRequestParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteAuthSessionByID(ctx context.Context, id uuid.UUID) error
	DeleteSessionByID(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetAgentRequestByID(ctx context.Context, id uuid.UUID) (AgentRequest, error)
	GetAuthSessionByID(ctx context.Context, id uuid.UUID) (AuthSession, error)
	GetAuthSessionByUserID(ctx context.Context, userID uuid.UUID) ([]AuthSession, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByReference(ctx context.Context, reference pgtype.Text) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListDocAgentRequests(ctx context.Context, acceptedBy pgtype.UUID) ([]AgentRequest, error)
	UpsertAuthSession(ctx context.Context, arg UpsertAuthSessionParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
