// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, vid, reference, ended_at, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	Vid       uuid.UUID          `json:"vid"`
	Reference pgtype.Text        `json:"reference"`
	EndedAt   pgtype.Timestamptz `json:"endedAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.Vid,
		arg.Reference,
		arg.EndedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, vid, reference, ended_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.Reference,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByReference = `-- name: GetSessionByReference :one
SELECT id, vid, reference, ended_at, created_at FROM sessions WHERE reference = $1
`

func (q *Queries) GetSessionByReference(ctx context.Context, reference pgtype.Text) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByReference, reference)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.Reference,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}
